services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - 15672:15672
      - 5672:5672

  database:
    image: postgres
    env_file: .env
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql/data

  server:
    image: sphericalpotatoinvacuum/soa-rest-server
    build:
      context: ../
      dockerfile: ./server/Dockerfile
    depends_on:
      - database
      - rabbitmq
    volumes:
      - user_pics:/server/user_pics
    ports:
      - 5000:5000

  worker:
    image: sphericalpotatoinvacuum/soa-rest-worker
    build:
      context: ../
      dockerfile: ./worker/Dockerfile
    depends_on:
      - database
      - rabbitmq

volumes:
  data:
  user_pics:
